import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // Premium dark system — deep charcoal surfaces, warm cream type,
  // bold orange accent. High-contrast, spacious, conversion-focused.
  '--slot4-page-bg': '#0f100f',
  '--slot4-page-text': '#f0ede8',
  '--slot4-panel-bg': '#171816',
  '--slot4-surface-bg': '#131412',
  '--slot4-muted-text': '#a8a6a0',
  '--slot4-soft-muted-text': '#6a6864',
  '--slot4-accent': '#ff7426',
  '--slot4-accent-fill': '#ff7426',
  '--slot4-accent-soft': '#2c1508',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#080908',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#1e1f1d',
  '--slot4-cream': '#141513',
  '--slot4-warm': '#0d0e0d',
  '--slot4-lavender': '#191a18',
  '--slot4-gray': '#161715',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0f100f',
  '--editable-page-text': '#f0ede8',
  '--editable-container': '1440px',
  '--editable-border': '#272825',
  '--editable-nav-bg': '#0f100f',
  '--editable-nav-text': '#f0ede8',
  '--editable-nav-active': '#ff7426',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#ff7426',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#171816',
  '--editable-footer-bg': '#090a09',
  '--editable-footer-text': '#f0ede8',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_6px_rgba(0,0,0,0.18)]',
  shadowStrong: 'shadow-[0_8px_40px_rgba(0,0,0,0.32)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.82))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-10',
    sectionY: 'py-20 sm:py-24 lg:py-32',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-14 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[148px] shrink-0 snap-start sm:w-[168px]',
  },
  type: {
    eyebrow: 'text-[11px] font-bold uppercase tracking-[0.32em] text-[var(--slot4-accent)]',
    heroTitle: 'text-[2.75rem] font-bold leading-[1.05] tracking-[-0.04em] sm:text-6xl lg:text-[4.25rem]',
    sectionTitle: 'text-[2rem] font-bold tracking-[-0.03em] sm:text-[2.5rem] lg:text-[3rem]',
    body: 'text-[15px] leading-[1.8]',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2.5 rounded-xl bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-bold tracking-[0.01em] text-white shadow-[0_2px_12px_rgba(255,116,38,0.38)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_8px_24px_rgba(255,116,38,0.42)] active:scale-[0.97]`,
    secondary: `inline-flex items-center justify-center gap-2.5 rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3.5 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)]/60 hover:text-[var(--slot4-accent)] hover:-translate-y-0.5 active:scale-[0.97]`,
    accent: `inline-flex items-center justify-center gap-2.5 rounded-xl ${editablePalette.accentBg} px-7 py-3.5 text-sm font-bold text-white shadow-[0_2px_12px_rgba(255,116,38,0.38)] transition duration-300 hover:-translate-y-0.5 active:scale-[0.97]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[3/4]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_20px_56px_rgba(0,0,0,0.28)]',
    fade: 'transition duration-300 hover:opacity-75',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
